### ISSUE TITLE
build error2

### ISSUE THREAD

**Issue by 666threesixes666** [etam/fortuna#2]
#include lessthan iostream greaterthan

above needs added to https://github.com/etam/fortuna/blob/master/src/fortuna_client/options.cpp

now to actually test this =D  thanks for the work

fortunad -s /tmp/fortunad.socket
terminate called after throwing an instance of 'fortuna::FortunaException'
  what():  generator is not seeded: 
Aborted

**Comment by etam** [comment]
1. "#include" - I assume there was something more, but got consumed by formatting engine.
2. I have no build errors under gcc and clang, so I still don't know what needs fixing.
3. I cannot reproduce your "generator is not seeded" error. Please provide more details.

**Comment by 666threesixes666** [comment]
doh! funtoo amd64 gcc, basically im looking to add fortuna to gentoo/funtoo's ebuild list, but it has to work out of the box, or be patchable.  this box is about fried from generating documentation and installing hurricanes of garbage.  i plan on formatting in 2 days or less.  what would you like /var/log/messages, dmesg?  i have a fresh laptop i can throw this on and test against a clean machine.

**Comment by etam** [comment]
I've submitted a patch 1eb1769

**Comment by etam** [comment]
Try rebuilding the whole project from scratch (use "make distclean && ./configure && make"). If you still get the "generator is not seeded" error, try using gdb to get the backtrace.

**Comment by 666threesixes666** [comment]
again fetching vanilla zip from your git repo, builds fine now...  still not seeded, im emerging gdb, ill append to this thread post in a moment.

**Comment by etam** [comment]
Are you sure you have no old version of libfortuna somewhere in /usr/lib64 or /usr/local/lib64?

**Comment by 666threesixes666** [comment]
ok ill throw it on the laptop in a second, im absolutely positive it's sterile of fortuna in all invocations, it was just installed like a week ago and doesn't have much on it.

**Comment by etam** [comment]
I've made a fix that might help: 2d7254d
Please check if it works.

**Comment by 666threesixes666** [comment]
fortuna-2d7254d90130ff46fc743eacf667b7efebf4d3f2 still same error regarding being unseeded.  its also making sockets where ever i issue the fortunad command.  thanks =D

**Comment by etam** [comment]
Removing socket on exit was added in patch 1e3ebf8

**Comment by etam** [comment]
So, I've got another idea:
Build the project with debugging enabled (`CXXFLAGS='-g' ./configure && make && sudo make install`).
Next run the fortunad in gdb with breakpoint. Make sure, that in file src/libfortuna/accumulator.cpp at line 60 there is `throw FortunaException::generator_is_not_seeded();`.
It should look like this:

    $ gdb fortunad
    [...]
    (gdb) b accumulator.cpp:60
    No source file named accumulator.cpp.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 1 (accumulator.cpp:60) pending.
    (gdb) r

If execution falls in trap, type `bt` (short for `backtrace`) and paste here the output.

**Comment by etam** [comment]
And there's no need to run `fortunad` as root with sudo.

**Comment by etam** [comment]
Now it's line 61

**Comment by 666threesixes666** [comment]
new system configurations = root + sudo lol not used to it...  sorry i formatted the desktop yesterday and am scrambling to get everything back to where it was.  ill return shortly, like in 3 days...  maybe add a patch remove socket upon crash / interruption?  thanks for everything, i know how much trouble doing these things are for you.  ill get gdb going and try to make sense of the 4th comment back.

**Comment by etam** [comment]
Those backtraces looks very strange. I've made a fix in patch ece7dae. Could you try again?

**Comment by 666threesixes666** [comment]
ece---
spaceball1 forthetuna # fortunad 
error: seed file error: could not open seed file

Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (accumulator.cpp:61) pending.
(gdb) r
Starting program: /usr/bin/fortunad 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
error: seed file error: could not open seed file
[Inferior 1 (process 25282) exited with code 01]
(gdb) bt
No stack.

**Comment by etam** [comment]
This time it's expected behaviour :)
But I forgot to add a note about it to README, so I did: 4ca2fc44

**Comment by etam** [comment]
And I found another bug #3 - it should still be possible to start fortunad, but nothing will be able to connect to it.
I'll fix it later today.

**Comment by 666threesixes666** [comment]
many many thanks sir =D

**Comment by etam** [comment]
bug #3 fixed.

**Comment by 666threesixes666** [comment]
Breakpoint 1 (accumulator.cpp:61) pending.
(gdb) r
Starting program:  
No executable file specified.
Use the "file" or "exec-file" command.

**Comment by etam** [comment]
Please, try again, but this time think about what you're doing. And read carefully about the seed file in README.

**Comment by 666threesixes666** [comment]
/var/lib/misc/random-seed is where my os saves a random seed for urandom.
fortuna_client -l 64 works great!
rngtest: bits received from input: 400000000
rngtest: FIPS 140-2 successes: 19977
rngtest: FIPS 140-2 failures: 22
what im trying to do is accelerate /dev/random with more than 1 source of entropy.  haveged is good but i need another. =)  could you have the program create a seed upon start?  or set it up so it ships with a predictable seed then rotate it a few times until it becomes unpredictable?

**Comment by etam** [comment]
Sorry for delay. Had some busy days.

> what im trying to do is accelerate /dev/random with more than 1 source of entropy. haveged is good but i need another. =)

Fortuna is not an entropy source. It's like /dev/urandom - it collects entropy from different sources and produces random bytes. Currently implemented entropy sources are rather poor compared to what kernel has. Feeding that into /dev/random won't improve the randomness and may even worsen it. Anyway, this bug report is not a good place for discussion on that topic.

> could you have the program create a seed upon start? or set it up so it ships with a predictable seed then rotate it a few times until it becomes unpredictable?

Absolutely no. Such actions are only weakening randomness provided by Fortuna. Also you could write bash scripts to achieve what you want without modifying the program. Again, this bug report is not a good place for discussion on that topic.

Back to main topic: Does fortuna compile and run for you? Can we close this issue?

**Comment by 666threesixes666** [comment]
oh yes, absolutely...  i must of forgotten to mention that it builds and runs good once a random seed is fed to it.  thanks very much etam =)
