### ISSUE TITLE
OS X: 2 errors with Automake

### ISSUE THREAD

**Issue by SkyCrawl** [etam/fortuna#4]
Hello, trying to install fortuna now and I've encountered two errors when executing `automake --add-missing`:

```
configure.ac:47: error: required file 'build-aux/ltmain.sh' not found
configure.ac:40: error: required file 'config.h.in' not found
```

The same command also complains that folder `./build-aux` doesn't exist but that can be resolved by creating it manually.

Despite the above errors, `configure` file has been generated so I'll try to go on :).

Note: I'm running latest OS X El Capitan (10.11.6).

**EDIT:**  
Because of that, `./configure` seems to fail:

```
config.status: error: cannot find input file: `Makefile.in'
```

**Comment by SkyCrawl** [comment]
My bad... if anyone encounters these errors, this is the procedure to follow:

```
$ autoreconf --install
$ aclocal
$ autoconf

# OPTIONALLY:
$ mkdir build-aux

$ automake --add-missing
```

In my case, I didn't call `autoreconf --install`, hence the errors.

**Comment by etam** [comment]
I think `autoreconf --install` should be enough.
Its documentation says it does:
> Run 'autoconf' (and 'autoheader', 'aclocal', 'automake', 'autopoint' (formerly 'gettextize'), and 'libtoolize' where appropriate) repeatedly to remake the GNU Build System files [...]
